### ISSUE TITLE
ImportError: No module named snmp

### ISSUE THREAD

**Issue by JBoisseau** [ronhanson/python-dcitools#1]
Hi,
'python bin/python doremiapi' fails : 

Traceback (most recent call last):
  File "doremiapi", line 15, in <module>
    import dcitools.devices.doremi.snmp as doremi_snmp
  File "/usr/local/lib/python2.7/dist-packages/dcitools-0.4.3-py2.7.egg/dcitools/devices/doremi/__init__.py", line 3, in <module>
    from . import snmp
  File "/usr/local/lib/python2.7/dist-packages/dcitools-0.4.3-py2.7.egg/dcitools/devices/doremi/snmp.py", line 11, in <module>
    from tbx.snmp import snmp_get
ImportError: No module named snmp

I only installed dcitools from github and tbx:
https://github.com/ronhanson/python-tbx

I tried on 2 OS : 
centos6.9, python 2.6, and raspbian, python2.7.13

Please assist

**Comment by ronhanson** [comment]
Hi Jeremy,
Truth is that library hasn't been updated since long. Still I think the code is still valid and would be easy to extend.
Still I will correct this today and will make it work again.
I will give more news soon.

**Comment by ronhanson** [comment]
Hey,
I've just refreshed a bit the repo with updated requirements and missing function.
This should solve your issue.
Do not hesitate if you encounter any problem, I'll be glad to help.

**Comment by JBoisseau** [comment]
Perfect, it works.
Many Thanks
